
CREATE TABLE imp_spider_loans (
	imp_loan_id				        serial primary key,
	phone_number					varchar(100), 
	Name		 				    varchar(256),
	disbursal_reference             varchar(100),
	date_granted                    varchar(50),
	due_date                        varchar(50),
	amount_granted                  varchar(50),
	total_granted                   varchar(20),
	repayment_reference             varchar(100),
    date_of_payment                 varchar(20),
    principle_payment               varchar(20),
    running_balance                 varchar(20),
    total_principle                 varchar(20),
    interest_payments               varchar(20),
    running_interest                varchar(20),
    total_interests                 varchar(20),
    total_due_loan_interest         varchar(20),
    overdue_period                  varchar(100),
    days_0_30                       varchar(10),
    days_31_60                      varchar(10),
    days_61_90                      varchar(10),
    days_above_90                   varchar(10),
    loan_code                       varchar(10)
);

CREATE TABLE imp_add_loans (
	imp_loan_id				        serial primary key,
	phone_number					varchar(100), 
	Name		 				    varchar(256),
	disbursal_reference             varchar(100),
	date_granted                    varchar(50),
	due_date                        varchar(50),
	amount_granted                  varchar(50),
	total_granted                   varchar(20),
	repayment_reference             varchar(100),
    date_of_payment                 varchar(20),
    principle_payment               varchar(20),
    running_balance                 varchar(20),
    total_principle                 varchar(20),
    interest_payments               varchar(20),
    running_interest                varchar(20),
    total_interests                 varchar(20),
    total_due_loan_interest         varchar(20),
    overdue_period                  varchar(100),
    days_0_30                       varchar(10),
    days_31_60                      varchar(10),
    days_61_90                      varchar(10),
    days_above_90                   varchar(10),
    loan_code                       varchar(10)
);
